### ISSUE TITLE
Compatibility with ForwardDiff?

### ISSUE THREAD

**Issue by ikirill** [JuliaDiff/TaylorSeries.jl#124] opened 2017-09-22 21:02 UTC
It seems ForwardDiff expects inputs to be `<:Real`, but Taylor series is `<:Number`. I'm not sure if that's on purpose, so I'm reporting it here.

```
julia> using TaylorSeries, ForwardDiff
INFO: Recompiling stale cache file /Users/kirill/.julia/lib/v0.6/TaylorSeries.ji for module TaylorSeries.

julia> cos(Taylor1([1.0, 2.0]))
 0.5403023058681398 - 1.682941969615793 t + 𝒪(t²)

julia> ForwardDiff.derivative(sin, Taylor1([1.0, 2.0]))
ERROR: MethodError: no method matching derivative(::Base.#sin, ::TaylorSeries.Taylor1{Float64})
Closest candidates are:
  derivative(::Any, ::Any, ::Any, ::ForwardDiff.DerivativeConfig) at /Users/kirill/.julia/v0.6/ForwardDiff/src/derivative.jl:7
  derivative(::F, ::R<:Real) where {F, R<:Real} at /Users/kirill/.julia/v0.6/ForwardDiff/src/derivative.jl:18
  derivative(::F, ::AbstractArray, ::R<:Real) where {F, R<:Real} at /Users/kirill/.julia/v0.6/ForwardDiff/src/derivative.jl:30
  ...
```

Changing it to be a subtype of Real seems to work, but I'm not sure if it relies on being Number rather than Real anywhere.
```
diff --git a/src/constructors.jl b/src/constructors.jl
index c9da264..3ee5dd0 100644
--- a/src/constructors.jl
+++ b/src/constructors.jl
@@ -12,7 +12,7 @@
 Parameterized abstract type for [`Taylor1`](@ref),
 [`HomogeneousPolynomial`](@ref) and [`TaylorN`](@ref).
 """
-@compat abstract type AbstractSeries{T<:Number} <: Number end
+@compat abstract type AbstractSeries{T<:Number} <: Real end


 ## Constructors ##
@@ -187,7 +187,7 @@ TaylorN(nv::Int; order::Int=get_order()) = TaylorN(Float64, nv, order=order)


 # A `Number` which is not an `AbstractSeries`
-const NumberNotSeries = Union{setdiff(subtypes(Number), [AbstractSeries])...}
+const NumberNotSeries = Union{setdiff(subtypes(Real), [AbstractSeries])...}

 # A `Number` which is not a TaylorN nor a HomogeneousPolynomial
 const NumberNotSeriesN =
```

```
julia> ForwardDiff.derivative(sin, Taylor1([1.0, 2.0]))
 0.5403023058681398 - 1.682941969615793 t + 𝒪(t²)

julia> cos(Taylor1([1.0, 2.0]))
 0.5403023058681398 - 1.682941969615793 t + 𝒪(t²)
```

**Comment by lbenet** [comment] 2017-09-22 21:16
I think in both cases this is done by design; do you agree @jrevels ?

In the case of TaylorSeries, this is done because, in some cases, you are interested to have expansion of complex funcions. The following is an example:
```julia
julia> using TaylorSeries

julia> exp( im*Taylor1(5) )
  ( 1.0 ) + ( 1.0 im ) t  - ( 0.5 ) t² - ( 0.16666666666666666 im ) t³  + ( 0.041666666666666664 ) t⁴ + ( 0.008333333333333333 im ) t⁵ + 𝒪(t⁶)

julia> ans^2
  ( 1.0 ) + ( 2.0 im ) t  - ( 2.0 ) t² - ( 1.3333333333333333 im ) t³  + ( 0.6666666666666666 ) t⁴ + ( 0.26666666666666666 im ) t⁵ + 𝒪(t⁶)
```

What it surprises me from your solution, which otherwise is absolutely acceptable, is that it seems
that you changed `NumberNotSeries` and `AbstractSeries`, but not the constructors itself. Would my example still work with your solution?

**Comment by ikirill** [comment] 2017-09-23 02:44
No, it wouldn't, that's a good point. I have to say, I just tried to find a minimal change that would get *my* example to work: getting the Taylor series for the solution of a nonlinear coupled ODE system, `x'=f(x); y'=-Jac(f(x))'*y` by repeatedly substituting `(x,y)` as a Taylor series, which involves taking the Jacobian at a Taylor series rather than a number.

I'm not even sure my example *has* to work, it's more that I sort of expected ForwardDiff to work, but it didn't, that was surprising because the reason seemed so minor, so I thought it was worth mentioning.

**Comment by lbenet** [comment] 2017-09-23 13:51
Regarding ODEs, I recommend to take a look on [TaylorIntegration.jl](https://github.com/PerezHz/TaylorIntegration.jl), which is the actual goal; take a look on the examples there, since we have not yet written the documentation. 

If I understand correctly, the case you are interested is something like the integration of the ODEs together with the first variational, which we construct using TaylorSeries. So far, it is not the most optimal way of doing it, but we are working on that. 

You are certainly welcome to contribute in either of the packages!

**Comment by ikirill** [comment] 2017-09-23 17:30
@lbenet That's pretty neat. I wrote the same thing as jetcoeffs!, but I wanted to call it like this:

```
    # rhs(t, x) = x
    rhs(t, x) = ForwardDiff.derivative(x -> 0.5x^2, x) # no method
    x0T = Taylor1(1.0, 8)
    TaylorIntegration.jetcoeffs!(rhs, Taylor1(), x0T)
    @show x0T - exp(Taylor1(x0T.order))
    x0T
```

**Comment by lbenet** [comment] 2017-09-23 21:06
The current implementation (master) of `jetcoeffs!` is a bit slow and uses too much memory. We are working on improving this, which uses some internals of TaylorSeries to avoid repeating operations, and creating too many auxiliaries. Simple cases yield a 4-5 x speed up! However, some local issues have distracted me...

**Comment by lbenet** [comment] 2017-10-08 15:08
Can I close this?

**Closed** 2017-10-13 03:15 UTC
