### ISSUE TITLE
Stange behaviour when Taylor1 pass to Taylor1 constructor.

### ISSUE THREAD

**Issue by davidalencia** [JuliaDiff/TaylorSeries.jl#300] opened 2022-05-04 23:03 UTC
When passing a Taylor1 structure to a Taylor1 constructor it returns a Taylor1{Taylor1{Int}}
Taking increasingly more time and memory.

A possible fix is to block this behavior or to create a copy of the Taylor1 struct passed to the constructor.

<img width="1038" alt="image" src="https://user-images.githubusercontent.com/20330355/166838852-072c3772-bd38-4e4e-8ef7-354b22fdd420.png">

**Comment by lbenet** [comment] 2022-05-05 22:33
Thanks for opening this! Before going any further let me point out some related issues/PRs: #12, #123, #126. 

Let me begin saying that this is "a feature" rather than a bug, in the sense that it is there by design as an alternative to `TaylorN`, with advantages and disadvantages. You can think of a polynomial in two (or more variables) variables as a polynomial in one variable, whose coefficients are polynomials in the other variable(s); this is precisely what these nested Taylor1 allow. Among the advantages I can mention that certain polynomial factorizations are possible (which is not allowed when using `TaylorN`), it is more flexible as you may have distinct variables with distinct orders (`TaylorN` fixes the order for all variables) and it avoids problems related to nested differentiation (see [this comment](https://github.com/JuliaDiff/TaylorSeries.jl/issues/232#issuecomment-970496123)). Among the disadvantages the interface is not transparent, friendly or clear (see #126), and it certainly has problems with memory production, as you point out. 

All in all, and until we have a more efficient multivariate solution (see #246, or #85 for a limitation of our approach), I think it is worth having it around, though I agree that we should address some current implementation limitations.

**Comment by lbenet** [comment] 2022-09-24 00:10
Closing. Feel free to reopen this issue.

**Closed by lbenet** 2022-09-24 00:10 UTC
